{% set name = "napari-sim-processor" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-sim-processor-{{ version }}.tar.gz
  sha256: 0e888a30621c0613dedbe1de94a1820aab01a77de85d699030e36fc744f30f78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  script_env:
    - QT_QPA_PLATFORM=offscreen

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - magicgui
    - matplotlib-base
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - superqt >=0.3.2

test:
  imports:
    - napari_sim_processor
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/andreabassi78/napari-sim-processor
  summary: A napari widget to process Structured Illumination Microscopy data with gpu acceleration
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andreabassi78
    - goanpeca
    - jaimergp
